### ISSUE TITLE
could not allocate memory, after many components using Vizzu have been loaded/reloaded

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/vizzu-lib#133]
vizzu.min.js:19 Uncaught RangeError: WebAssembly.Memory(): could not allocate memory
    at eval (vizzu.min.js:19:1)
    at new Vizzu (vizzu.min.js:19:1)
    at eval (ShareOfChart.js:158:1)
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)

**Comment by veghdev** [comment]
Is there a way to unimport on component unmount, or clean up WebAssembly memory?

**Comment by simzer** [comment]
Fixed  with commit: https://github.com/vizzuhq/vizzu-lib/pull/145/commits/762e691164f7dcd6f2f0b016e9a0c1c710ac1137

chart.detach() should be called to enable proper garbage collection
